variable "cloudwatch_log_expiration_days" {
  type    = number
  default = 90
}

variable "ec2_autoscale_instance_type" {
  type    = string
  default = "t3.micro"
}

variable "vpc_cidr_block" {
  type = string
}
variable "availability_zones" {
  type = list(string)
}

variable "build_image" {
  type        = string
  default     = "aws/codebuild/standard:2.0"
  description = "Docker image for build environment, e.g. 'aws/codebuild/standard:2.0' or 'aws/codebuild/eb-nodejs-6.10.0-amazonlinux-64:4.0.0'. For more info: http://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref.html"
}

variable "allow_encrypted_uploads_only" {
  type    = bool
  default = false
}

variable "allow_ssl_requests_only" {
  type    = bool
  default = true
}

variable "enable_mfa_delete" {
  type        = bool
  default     = false
  description = "Set this to true to enable MFA on bucket. You must also set `versioning_enabled` to `true`."
}

variable "access_log_bucket_name" {
  type        = string
  default     = ""
  description = "Name of the S3 bucket where S3 access logs will be sent to"
}

variable "access_log_bucket_prefix_override" {
  type        = string
  default     = ""
  description = "Prefix to prepend to the current S3 bucket name, where S3 access logs will be sent to"
}

variable "s3_object_ownership" {
  type        = string
  default     = "BucketOwnerEnforced"
  description = "Specifies the S3 object ownership control. Valid values are `ObjectWriter`, `BucketOwnerPreferred`, and 'BucketOwnerEnforced'."
}

variable "s3_source_policy_documents" {
  type        = list(string)
  default     = []
  description = <<-EOT
    List of IAM policy documents that are merged together into the exported document.
    Statements defined in source_policy_documents must have unique SIDs.
    Statement having SIDs that match policy SIDs generated by this module will override them.
    EOT
}

variable "artifact_sns_topic_arn" {
  type    = string
  default = ""
}

variable "kms_key_deletion_window_in_days" {
  type    = number
  default = 30
}

variable "kms_key_enable_key_rotation" {
  type    = bool
  default = true
}

variable "overwrite_ssm_parameters" {
  type    = bool
  default = false
}

variable "slack_notifications_enabled" {
  type    = bool
  default = false
}

variable "slack_channel_ids" {
  type    = list(string)
  default = []
}

variable "slack_token_secret_arn" {
  type    = string
  default = ""
}

variable "slack_token_secret_kms_key_arn" {
  type    = string
  default = ""
}

variable "ssm_deploy_document_name" {
  type    = string
  default = ""
}

variable "buildspec" {
  type    = string
  default = ""
}

variable "ssm_document_target_key_name" {
  type    = string
}

variable "ssm_document_target_key_values" {
  type    = string
}

variable "buildspec_env_vars" {
  type    = list(any)
  default = []
}

variable "buildspec_policy_docs" {
  type    = list(string)
  default = []
}